SET SERVEROUTPUT ON;

-- CREAMOS LA BASE DE DATOS
CREATE TABLE EMPLEADO (ID INTEGER PRIMARY KEY,NOMBRE VARCHAR2(60),SUELDO_BASE FLOAT);

--INSERTAMOS LOS REGISTROS
INSERT INTO EMPLEADO values(1,'ama',400);
INSERT INTO EMPLEADO values(2,'juan',350);
INSERT INTO EMPLEADO values(3,'pedro',600);
INSERT INTO EMPLEADO values(4,'luis',520);

SELECT * FROM EMPLEADO;

--CURSOR IMPLICITO ES UNA SOLA OCURRENCIA

DECLARE
NUM_EMPLEADO INTEGER;
begin

--EL SIGUIENTE ES EL CURSOR 

SELECT COUNT(*) INTO NUM_EMPLEADO FROM EMPLEADO;
DBMS_OUTPUT.PUT_LINE('LOS EMPLEADOS SON '||NUM_EMPLEADO);
END;
/

